spring:
  config:
    import:
      - optional:file:.env[.properties]
      - optional:file:../.env[.properties]
      - optional:file:Backend/demo/.env[.properties]

  datasource:
    url: jdbc:mysql://localhost:3306/stretto_db?createDatabaseIfNotExist=true
    username: ${db_usuario:root}
    password: ${db_password:}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${mail_usuario:}
    password: ${mail_password:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret: ${JWT_SECRET:strettoSecretKeyForJwtTokenSigning12345678901234567890}
  expiration: 86400000

jwt_secret: ${JWT_SECRET:strettoSecretKeyForJwtTokenSigning12345678901234567890}